services:  
  multi_robots:
    container_name: multi_robots-dev
    build: 
      context: ..
      dockerfile: Docker/Dockerfile
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}     
    volumes:
      - ../:/root/multi_robots_ws #mount project directory to local computer
      - builds:/root/multi_robots_ws/build #send build files to docker volume
      - logs:/root/multi_robots_ws/log
      - installs:/root/multi_robots_ws/install
    stdin_open: true    # Keep stdin open for an interactive shell
    tty: true    
    command: > 
      bash -c "exec bash"

volumes:
  builds:
  logs:
  installs: